"""Jira issue field builders using Atlassian Document Format (ADF)."""

from __future__ import annotations

from src.config import settings
from src.schemas.events import PROpenedEvent


def _text_node(text: str) -> dict:
    return {"type": "text", "text": text}


def _bold_text(text: str) -> dict:
    return {"type": "text", "text": text, "marks": [{"type": "strong"}]}


def _link_node(text: str, href: str) -> dict:
    return {
        "type": "text",
        "text": text,
        "marks": [{"type": "link", "attrs": {"href": href}}],
    }


def _paragraph(*inline: dict) -> dict:
    return {"type": "paragraph", "content": list(inline)}


def _heading(text: str, level: int = 3) -> dict:
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [_text_node(text)],
    }


def build_issue_fields(event: PROpenedEvent) -> dict:
    """Build Jira create-issue fields dict for a PR-opened event."""
    severity_label = "BREAKING" if event.is_breaking else event.severity.upper()
    summary = f"[ACCR] Remediation PR for {event.target_service} — review required"

    routes_text = ", ".join(event.changed_routes) if event.changed_routes else "N/A"

    description_doc = {
        "version": 1,
        "type": "doc",
        "content": [
            _heading("Contract Change Details"),
            _paragraph(
                _bold_text("Severity: "),
                _text_node(f"{severity_label} ({event.severity})"),
            ),
            _paragraph(
                _bold_text("Summary: "),
                _text_node(event.summary or "Contract change detected"),
            ),
            _paragraph(
                _bold_text("Changed routes: "),
                _text_node(routes_text),
            ),
            _heading("Remediation"),
            _paragraph(
                _bold_text("Target service: "),
                _text_node(event.target_service),
            ),
            _paragraph(
                _bold_text("Pull request: "),
                _link_node(event.pr_url, event.pr_url),
            ),
            _paragraph(
                _bold_text("Devin session: "),
                _link_node(event.devin_session_url, event.devin_session_url),
            ),
            _heading("Action Required"),
            _paragraph(
                _text_node("Review and merge the pull request linked above. "
                           "This PR was generated by Devin as part of automated contract change remediation."),
            ),
        ],
    }

    fields: dict = {
        "project": {"key": settings.jira_project_key},
        "summary": summary,
        "description": description_doc,
        "issuetype": {"name": "Task"},
        "labels": ["contract-change", "devin-remediation"],
    }
    if settings.jira_assignee_account_id:
        fields["assignee"] = {"accountId": settings.jira_assignee_account_id}

    return fields
